# Generated by Django 5.1.4 on 2024-12-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelsInterface', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='ModelInterface',
        ),
    ]
