# Generated by Django 5.1.4 on 2024-12-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMeta', '0002_rename_model_modelinterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
