# Generated by Django 5.1.4 on 2025-01-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiMeta', '0004_alter_apikey_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinterface',
            name='image_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelinterface',
            name='text_completions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modelinterface',
            name='vision',
            field=models.BooleanField(default=False),
        ),
    ]
